//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFLClient.ResourceManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TFLClientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TFLClientResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TFLClient.ResourceManager.TFLClientResources", typeof(TFLClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Your authentication credentials were missing or incorrect.
        /// </summary>
        internal static string TflApiRequestErrorCodeException_ApiCredentialsError {
            get {
                return ResourceManager.GetString("TflApiRequestErrorCodeException_ApiCredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: There&apos;s no API method specified to be invoked. Please follow the following format:
        ///      &lt;ApiMethod&gt; &lt;Parameter1, Parameter2, ...&gt;.
        /// </summary>
        internal static string TflApiRequestErrorCodeException_EmptyParameters {
            get {
                return ResourceManager.GetString("TflApiRequestErrorCodeException_EmptyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Internal server error.
        /// </summary>
        internal static string TflApiRequestErrorCodeException_Generic_ApiInternalError {
            get {
                return ResourceManager.GetString("TflApiRequestErrorCodeException_Generic_ApiInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0} is not a valid road.
        /// </summary>
        internal static string TflApiRequestErrorCodeException_GetRoadStatus_RoadNotFound {
            get {
                return ResourceManager.GetString("TflApiRequestErrorCodeException_GetRoadStatus_RoadNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Couldn&apos;t find a suitable handler. &apos;{apiMethod}&apos; is an invalid API Method.
        /// </summary>
        internal static string TflApiRequestErrorCodeException_InvalidAPIMethod {
            get {
                return ResourceManager.GetString("TflApiRequestErrorCodeException_InvalidAPIMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid or empty parameters passed in for the API method &apos;{apiMethod}&apos;.
        /// </summary>
        internal static string TflApiRequestErrorCodeException_InvalidAPIParameters {
            get {
                return ResourceManager.GetString("TflApiRequestErrorCodeException_InvalidAPIParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status of the {displayName} is as follows
        ///           Road Status is {statusSeverity}
        ///           Road Status Description is {statusSeverityDescription}.
        /// </summary>
        internal static string TflApiResult_RoadStatus {
            get {
                return ResourceManager.GetString("TflApiResult_RoadStatus", resourceCulture);
            }
        }
    }
}
